version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 8090:80
    links:
      - fpm
    volumes:
      - .:/var/www/krppo-logger
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
      - .:/var/www/krppo-logger
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
    - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=krppo_logger
